#shop_data_grid_generator:
#    resource: "@ShopDataGridGeneratorBundle/Controller/"
#    type:     annotation
#    prefix:   /

shop_back_office:
    resource: "@ShopBackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /admin/

shop_front_office:
    resource: "@ShopFrontOfficeBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
fos_user:
    resource: "@ShopUserBundle/Resources/config/routing/all.xml"